name: API CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - run: go version
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: api
      - run: make generate
      - run: make build
